sudo: false

language: java
jdk:
  - oraclejdk8

cache:
    directories:
        - $HOME/.m2

before_cache:
    - rm -rf $HOME/.m2/repository/com/itdhq

before_script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then base64 -d <<< $MAVEN_DEPLOY_SETTINGS | tar -xz -C $HOME; fi'

script:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then export FINAL_PHASE=deploy; else export FINAL_PHASE=package; fi'
    - mvn clean package && mvn -pl platform-jar,maven-plugin $FINAL_PHASE

notifications:
  email:
    on_success: change
    on_failure: always
